#!/bin/bash
rm $HOME/instt > /dev/null 2>&1
rm /root/instt > /dev/null 2>&1
rm $HOME/Plus > /dev/null 2>&1
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1

cd
wget http://$link/$_key_/vip-vps.sh > /dev/null 2>&1; bash vip-vps.sh
sleep 1

cat /dev/null > ~/.bash_history && history -c
rm $HOME/instt > /dev/null 2>&1
rm /root/instt > /dev/null 2>&1
rm $HOME/Plus > /dev/null 2>&1
service apache2 restart > /dev/null 2>&1