#!/bin/bash

#######################################################
rm /root/pkeyssh > /dev/null 2>&1
rm $HOME/pkeyssh > /dev/null 2>&1
rm /bin/keyssh > /dev/null 2>&1
rm /var/www/html/Plus > /dev/null 2>&1
rm /home/instt > /dev/null 2>&1
rm /home/vip-vps.sh > /dev/null 2>&1
#######################################################
clear
echo ""
echo -e "\033[1;34m ================================="
echo -e "\033[1;36m INICIANDO INSTALACAO"
echo ""
echo -e "\033[1;33m AGUARDE...UPDATE"
echo -e "\033[1;33m ATUALIZANDO LINUX PODE DEMORAR"
echo -e "\033[1;34m ================================="
apt-get update > /dev/null 2>&1
# apt-get upgrade -y
# > /dev/null 2>&1
echo ""
#######################################################
echo -e "\033[1;34m ================================="
echo -e "\033[1;36m INSTALANDO O APACHE2\033[0m"
echo ""
echo -e "\033[1;33m AGUARDE..."
echo -e "\033[1;34m ================================="
apt-get install apache2 -y > /dev/null 2>&1
sleep 4s
echo ""
#######################################################
echo -e "\033[1;34m ================================="
echo -e "\033[1;36m INSTALANDO SISTEMAS KEY\033[0m"
echo ""
echo -e "\033[1;33m AGUARDE..."
echo -e "\033[1;34m ================================="
cd /var/www/html
wget https://raw.githubusercontent.com/geralt99/KeySSH/master/Plus /Plus > /dev/null 2>&1
chmod +x /var/www/html/Plus
cd
#######################################################
cd /bin/
wget https://raw.githubusercontent.com/geralt99/KeySSH/master/keyssh > /dev/null 2>&1
chmod +x /bin/keyssh
cd
#######################################################
cd /home/
wget https://raw.githubusercontent.com/geralt99/KeySSH/master/instt > /dev/null 2>&1
chmod +x /home/instt
wget https://raw.githubusercontent.com/geralt99/KeySSH/master/vip-vps.sh > /dev/null 2>&1
cd
sleep 6s
echo ""
cat /dev/null > ~/.bash_history && history -c
#######################################################
echo -e "\033[1;34m ================================="
echo -e "       \033[1;31m ATENCAO"
echo -e "\033[1;36m MONTANDO O SEU LINK-IP\033[0m"
echo ""
echo -e "\033[1;33m AGUARDE..."
echo -e "\033[1;34m ================================="
IP=$(wget -qO- ipv4.icanhazip.com)
if [[ -e "/var/www/html/Plus" ]]; then
sed -i "s;SEU-IP-AKI;$IP;g" /var/www/html/Plus > /dev/null 2>&1
fi
sleep 6s
clear
#######################################################
echo ""
echo -e "\033[1;34m ================================="
echo -e "\033[1;32m PAINEL KEY INSTALADO COM SUCESSO!"
echo -e "\033[1;32m PARA  CRIAR  KEY  SSHPLUS"
echo ""
echo -e "\033[1;36m Digite: "keyssh" \033[1;37m\033[0m"
echo -e "\033[1;34m ================================="
cat /dev/null > ~/.bash_history && history -c
rm /root/pkeyssh > /dev/null 2>&1
rm $HOME/pkeyssh > /dev/null 2>&1
rm $HOME/pkeyssh.1 > /dev/null 2>&1