#!/bin/bash
rm $HOME/instt > /dev/null 2>&1
rm $HOME/Plus > /dev/null 2>&1
rm /root/Plus > /dev/null 2>&1
clear
IP=$(wget -qO- ipv4.icanhazip.com)
link="SEU-IP-AKI"
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
tput setaf 7 ; tput setab 4 ; tput bold ; printf '%40s%s%-12s\n' "BEM VINDO AO SSHPLUS MANAGER" ; tput sgr0
echo -e "\033[1;31m════════════════════════════════════════════════════\033[0m"
echo ""
echo -e "             \033[1;31mATENCAO! \033[1;33mESSE SCRIPT IRA !\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mINSTALAR UM CONJUNTO DE SCRIPTS COMO FERRAMENTAS\033[0m" 
echo -e "\033[1;33m  PARA O GERENCIAMENTO DE REDE, SISTEMA E USUARIOS\033[0m"
echo ""
echo -e "\033[1;32m• \033[1;32mDICA! \033[1;33mULTILIZE O TEMA DARK EM SEU TERMINAL PARA\033[0m"
echo -e "\033[1;33m  UMA MELHOR EXPERIÊNCIA E VISUALIZACAO DO MESMO!\033[0m"
echo ""
echo -e "\033[1;31m≠×≠×≠×≠×≠×≠×≠×≠×[\033[1;33m • \033[1;32mBY CRAZY VPN\033[1;33m •\033[1;31m ]≠×≠×≠×≠×≠×≠×≠×≠×\033[0m"
echo ""
echo -ne "\033[1;36mINFORME SUA KEY:\033[1;37m "; read _key_
if [[ -z $_key_ ]]; then
echo ""
echo -e "\033[1;31m KEY INVALIDA\033[1;32m"
sleep 1
clear; exit
fi
wget http://$link/$_key_/instt > /dev/null 2>&1
sleep 1
if [[ -f $HOME/instt ]]; then
echo -e "\n\033[1;32m KEY VALIDA ! \033[1;32m"
echo ""
sleep 2
source $HOME/instt
else
echo -e "\n\033[1;31m KEY INVALIDA !\033[0m"
rm $HOME/instt > /dev/null 2>&1
rm /root/Plus > /dev/null 2>&1
rm /root/Plus.1 > /dev/null 2>&1
sleep 2
clear; exit
fi
rm $HOME/instt > /dev/null 2>&1
rm $HOME/Plus > /dev/null 2>&1
rm $HOME/Plus.1 > /dev/null 2>&1